# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 11:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 8, 13, 11, 20, 45, 236917, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
